### ISSUE TITLE
bot log ending bankroll doesn't match engine?

### ISSUE THREAD

**Issue by clementou** [cmu-dsc/poker-engine-2024#27]
<img width="259" alt="Screenshot 2024-03-27 at 10 37 33" src="https://github.com/cmu-dsc/poker-engine-2024/assets/12637289/7fcddfd8-bb5a-4c84-870b-b01843387ebe">

<img width="911" alt="Screenshot 2024-03-27 at 10 37 43" src="https://github.com/cmu-dsc/poker-engine-2024/assets/12637289/46e0147c-835b-4fcf-9d70-2db21b981c88">

@dongkyuk can u take a look at this

**Comment by clementou** [comment]
<img width="747" alt="Screenshot 2024-03-27 at 10 40 43" src="https://github.com/cmu-dsc/poker-engine-2024/assets/12637289/a692992a-4b68-4ddb-b184-ee705cf36d24">

engine log

**Comment by dongkyunk** [comment]
wdym it doesn't match?? Both are 12000 right?
Also it doesn't say -11600 cuz the game ends before the bot has a chance to log

**Comment by clementou** [comment]
in the database it records the bankroll from the second to last round. the correct number from the last round is 12000 not 11600.

the database and the logs are written by the engine

we have board meeting right now!!

**Comment by dongkyunk** [comment]
Yeah so I don't understand what the problem is. 12000 is correct?

**Comment by clementou** [comment]
no it says 12000 on the log but it says 11600 on the database

12000 is correct

this line: https://github.com/cmu-dsc/poker-engine-2024/blob/master/engine/engine.py#L188

**Comment by clementou** [comment]
this doesn't happen for every game? wtf?

**Comment by clementou** [comment]
bogos binted
